compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

nodeLinker: pnp

npmScopes:
  dodopizza:
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-typescript: 3.6.1

progressBarStyle: simba

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.13.0.cjs
