approvedGitRepositories:
  - "**"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: true

nodeLinker: pnp

npmScopes:
  dodopizza:
    npmAuthToken: "${NPM_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@testing-library/jest-dom@*":
    peerDependencies:
      vitest: "*"
  bundle-require@*:
    dependencies:
      esbuild: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-typescript: 4.3.2
  local-pkg@*:
    dependencies:
      jsdom: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - .yarn/plugins/@dodopizza/node-version-check-plugin.cjs

progressBarStyle: simba

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.14.1.cjs
